# Generated by Django 4.1 on 2023-01-04 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0003_alter_resimler_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resimler",
            options={"get_latest_by": "created_at"},
        ),
        migrations.AddField(
            model_name="resimler",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resimler",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="resimler",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
