# Generated by Django 4.1 on 2023-01-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0005_resimler_catlak"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resimler",
            name="catlak",
        ),
        migrations.AddField(
            model_name="resimler",
            name="average_color",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
