# Generated by Django 4.1 on 2023-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0006_remove_resimler_catlak_resimler_average_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resimler",
            name="average_color",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
