# Generated by Django 4.1 on 2023-01-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0008_resimler_crack_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resimler",
            name="crack_image",
        ),
    ]
