# Generated by Django 4.1 on 2023-01-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0009_remove_resimler_crack_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="resimler",
            name="crack",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="resimler",
            name="dot",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="resimler",
            name="good",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="resimler",
            name="joint",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
