# Generated by Django 4.1 on 2023-01-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0010_resimler_crack_resimler_dot_resimler_good_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resimler",
            name="crack",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="resimler",
            name="dot",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="resimler",
            name="good",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="resimler",
            name="joint",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
