# Generated by Django 4.1 on 2023-01-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0011_alter_resimler_crack_alter_resimler_dot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resimler",
            name="kalite_turu",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
