# Generated by Django 4.1 on 2023-01-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0012_resimler_kalite_turu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resimler",
            name="crack",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="resimler",
            name="dot",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="resimler",
            name="good",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="resimler",
            name="joint",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
