# Generated by Django 4.1 on 2023-09-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0013_alter_resimler_crack_alter_resimler_dot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resimler",
            name="agir_hasarli",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="resimler",
            name="az_hasarli",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="resimler",
            name="orta_hasarli",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
